
HavenCoreBundle:
    resource: "@HavenCoreBundle/Resources/config/routing.yml"
    
HavenWebBundle:
    resource: "@HavenWebBundle/Resources/config/routing.yml"
    
HavenMediaBundle:
    resource: "@HavenMediaBundle/Resources/config/routing.yml"
    
HavenSecurityBundle:
    resource: "@HavenSecurityBundle/Resources/config/routing.yml"
    
HavenPosBundle:
    resource: "@HavenPosBundle/Resources/config/routing.yml"
    
HavenPortfolioBundle:
    resource: "@HavenPortfolioBundle/Resources/config/routing.yml"
    
HavenPersonaBundle:
    resource: "@HavenPersonaBundle/Resources/config/routing.yml"
    
HavenCmsBundle:
    resource: "@HavenCmsBundle/Resources/config/routing.yml"

HavenMediaBundle:
    resource: "@HavenMediaBundle/Resources/config/routing.yml"
       
    
_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
