<?php

namespace Haven\Bundle\PersonaBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Haven\Bundle\PersonaBundle\Entity\Persona;


/**
 * PersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonaRepository extends EntityRepository {

    private $query_builder;

    public function getQueryBuilder() {
        return $this->query_builder;
    }

    public function setQueryBuilder(\Doctrine\ORM\QueryBuilder $query_builder) {
        $this->query_builder = $query_builder;
    }

    public function findAll() {
        $this->query_builder = $this->createQueryBuilder("e");
        return $this->getResult();
    }

//    public function findAllPublished() {
//        $this->query_builder = $this->filterByStatus(Language::STATUS_PUBLISHED)->getQueryBuilder();
//        return $this->getResult();
//    }
//
//    public function findAllPublishedOrderedByRank($order = 'ASC') {
//        $this->query_builder = $this->filterByStatus(Persona::)
//                ->orderByRank($order)
//                ->getQueryBuilder();
//
//        return $this->getResult();
//    }

    private function filterByStatus($status) {
        if (is_null($this->query_builder))
            $this->query_builder = $this->createQueryBuilder("e");

        $this->query_builder->andWhere("e.status = :status");
        $this->query_builder->setParameter("status", $status);

        return $this;
    }

    private function orderByRank($order = 'ASC') {
        if (is_null($this->query_builder))
            $this->query_builder = $this->createQueryBuilder("e");

        $this->query_builder->orderBy("e.rank", $order);

        return $this;
    }

    public function getResult() {
        $query = $this->query_builder->getQuery();
        return $query->getResult();
    }

}