<?php

namespace Haven\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContentRepository extends EntityRepository {

//    public function getByNameLang($nom, $lang) {
//        $query = $this->createQueryBuilder("c")
//                        ->join("c.translations", "t")
//                        ->where('t.lang = :lang')
//                        ->andWhere('c.nom = :nom')
//                        ->setParameter('nom', $nom)
//                        ->setParameter('lang', $lang);
//        return $this->makeArray($query->getQuery()->getResult());
//    }

    public function getInListLang($noms, $lang) {
        $query = $this->createQueryBuilder("c");
        $query->select("c, t")
                ->join("c.translations", "t")
                ->where('c.actif = 1')
                ->andWhere('t.lang = :lang')
                ->andWhere($query->expr()->in('c.nom', $noms))
                ->setParameter('lang', $lang);
        return $this->makeArray($noms, $query->getQuery()->getResult());
    }

    private function makeArray($nom, $rows) {
        $cmsContents = \array_fill_keys($nom, null); //s'assure que tout les clés demandés existent dans l'array de retour
        foreach ($rows as $row) {
            $cmsContents[$row->getNom()] = $row;
        }
        return($cmsContents);
    }

}