<?php

namespace Haven\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository {

    private $query_builder;

    public function __construct($em, \Doctrine\ORM\Mapping\ClassMetadata $class) {
        parent::__construct($em, $class);
        $this->query_builder = $this->createQueryBuilder("m")
                ->leftJoin("m.translations", "t")
                ->leftJoin("t.trans_lang", "tl");
    }

    public function findRootMenus() {
        $this->filterByRoot();

        return $this->query_builder->getQuery()->getResult();
    }

    public function findRootMenuByName($name) {
        $query_builder = $this->createQueryBuilder("m")
                ->leftJoin("m.translations", "t")
                ->leftJoin("t.trans_lang", "tl");
        $query_builder->andWhere("m.id = m.root");
//        $this->filterByName($name);
         $query_builder->andWhere("t.name = :name");
        $query_builder->setParameter("name", $name);
        return $query_builder->getQuery()->getOneOrNullResult();
    }

    public function findByLocalizedSlug($slug, $language) {
//        $this->query_builder = $this->createBaseQueryBuilder();
        $this->filterByLang($language, $this->query_builder);
        $this->filterBySlug($slug, $this->query_builder);
//        $this->filterTranslationByStatus(PageTranslation::STATUS_PUBLISHED, $this->query_builder);

        return $this->query_builder->getQuery()->getOneOrNullResult();
    }

    public function getQueryBuilder() {

        return $this->query_builder;
    }

    private function filterByRoot() {

        $this->query_builder->andWhere("m.id = m.root");

        return $this;
    }

    private function filterBySlug($slug, $qb = null) {
//        $this->query_builder = ($qb) ? $qb : $this->createBaseQueryBuilder();

        $this->query_builder->andWhere("t.slug = :slug");
        $this->query_builder->setParameter("slug", $slug);

        return $this;
    }
    private function filterByName($name, $qb = null) {
//        $this->query_builder = ($qb) ? $qb : $this->createBaseQueryBuilder();

        $this->query_builder->andWhere("t.name = :name");
        $this->query_builder->setParameter("name", $name);

        return $this;
    }

    private function filterByLang($lang, $qb = null) {
//        $this->query_builder = ($qb) ? $qb : $this->createBaseQueryBuilder();

        $this->query_builder
//                ->leftJoin("t.trans_lang", "tl")
                ->andWhere("tl.symbol= :language")
                ->setParameter("language", $lang)
        ;
        return $this;
    }

}
