<?php

namespace Haven\Bundle\CmsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageTranslationRepository extends EntityRepository
{
}
