haven_mediabundle:
    resource: "@HavenWebBundle/Controller"
    type:     annotation
    prefix: /{_locale}/
    requirements:
      _locale: fr|en


#HavenWebBundle_Post:
#    resource: "@HavenWebBundle/Controller/PostController.php"
#    type:     annotation
#    prefix: /{_locale}/
#    defaults:
#      admin: admin
#    requirements:
#      _locale: fr|en