<?php

namespace Haven\Bundle\PersonaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StateRepository extends EntityRepository
{
    
    /**
* @Route("/stateByCountry", name="_stateByCountry")
*/
public  function listStateByCountryId()
{
    $this->em = $this->get('doctrine')->getEntityManager();
    $this->repository = $this->em->getRepository('HavenPersonaBundle:State');
 
    $communityId = $this->get('request')->query->get('data');
 
    $states = $this->repository->findByCommunity($Country_Id);
 
    if (empty($states)) {
        return new Response('<option>No states found for that community</option>');
    }
 
    $html = '';
    foreach($states as $state)
    {
        $html = $html . sprintf("<option value=\"%d\">%s</option>",$state->getId(), $state->getName());
    }
 
    return new Response($html);
}

}
